apiVersion: v1
kind: Service
metadata:
  name: producer
  labels:
    app: producer
spec:
  type: ClusterIP
  ports:
    - name: producer
      port: 9000
      targetPort: 9000
  selector:
    app: producer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: producer
spec:
  revisionHistoryLimit: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: 048610927396.dkr.ecr.eu-west-1.amazonaws.com/producer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: producer
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: producer
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50