apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  type: ClusterIP
  ports:
    - name: consumer
      port: 9001
  selector:
    app: consumer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consumer
spec:
  revisionHistoryLimit: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: 048610927396.dkr.ecr.eu-west-1.amazonaws.com/consumer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: consumer
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: consumer
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
